### ISSUE TITLE
Cannot change back to a character after selecting them, going to another, and going back.

### ISSUE THREAD

**Issue by KurokoShiroya** [AttorneyOnline/akashi#174] opened 2021-08-01 16:06 UTC
Bug: When you chose a character in the character select menu and then change to another, you can't change back to the first character you chose. Web also still counts characters you selected from days ago even if you close the tab, thus you cant select them as well.
How to reproduce: I used google chrome web mcc, go char selection, and for example, I choose Add (Elsword), and then change to Aisha (Elsword), then go BACK to Add, but I can't because it won't let me select him on the character select menu. The same thing goes for Aisha, and whatever characters you chose and go to another, and go back.
Version: Master

**Comment by MangosArentLiterature** [comment] 2021-08-01 16:22
I cannot reproduce this issue. Tested both latest master with 2.9.1 client, and WebAO on akashi server running latest master.

**Comment by in1tiate** [comment] 2021-08-01 19:36
I can't reproduce this either. Closing.

**Closed by in1tiate** 2021-08-01 19:36 UTC
